Introducing OSX Support!

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -3,8 +3,6 @@
 set -o pipefail
 
 
-TARGET_LIST=arm-softmmu,i386-softmmu,x86_64-softmmu,arm-linux-user,i386-linux-user,x86_64-linux-user
-
 QEMU_VERSION=`node -p "require('./package.json').version"`
 
 QEMU_URL=http://wiki.qemu-project.org/download/qemu-$QEMU_VERSION.tar.bz2
@@ -39,12 +37,36 @@ esac
 
 OS="`uname`"
 case $OS in
-  'Linux')     PLATFORM=linux   ;;
-  'FreeBSD')   PLATFORM=freebsd ;;
-  'WindowsNT') PLATFORM=win     ;;
-  'Darwin')    PLATFORM=mac     ;;
-  'SunOS')     PLATFORM=solaris ;;
-  'AIX')       PLATFORM=linux   ;;
+  'Linux')
+    PLATFORM=linux
+    AUDIO=alsa
+    TARGET_LIST=arm-softmmu,i386-softmmu,x86_64-softmmu,arm-linux-user,i386-linux-user,x86_64-linux-user
+    DISPLAY=sdl
+    OS_PRODUCTS=(bin libexec share)
+    ;;
+  'FreeBSD')
+    PLATFORM=freebsd
+    ;;
+  'WindowsNT')
+    PLATFORM=win
+    ;;
+  'Darwin')
+    PLATFORM=mac
+    AUDIO=coreaudio
+    TARGET_LIST=arm-softmmu,i386-softmmu,x86_64-softmmu
+    DISPLAY=cocoa
+    OS_PRODUCTS=(bin share)
+    ;;
+  'SunOS')
+    PLATFORM=solaris
+    ;;
+  'AIX')
+    PLATFORM=linux
+    AUDIO=alsa
+    TARGET_LIST=arm-softmmu,i386-softmmu,x86_64-softmmu,arm-linux-user,i386-linux-user,x86_64-linux-user
+    DISPLAY=sdl
+    OS_PRODUCTS=(bin libexec share)
+    ;;
 
   *)
     echo Unknown OS "$OS"
@@ -55,7 +77,7 @@ esac
 
 function rmStep(){
   rm -rf "$@"
-  rmdir -p --ignore-fail-on-non-empty `dirname "$@"`
+  #rmdir -p --ignore-fail-on-non-empty `dirname "$@"`
 }
 
 # Clean object dir and return the input error
@@ -72,7 +94,7 @@ function err(){
 SRC_DIR=`pwd`/deps/qemu
 OBJ_DIR=build/$MACHINE
 OUT_DIR=`pwd`
-PRODUCTS=(bin libexec share)
+PRODUCTS=$OS_PRODUCTS
 PREBUILD=prebuilds/$PLATFORM-$ARCH.tar.gz
 
 
@@ -104,10 +126,11 @@ if [[ ! -d $STEP_DIR ]]; then
     mkdir -p $STEP_DIR &&
     cd       $STEP_DIR || exit 5
 
+
     $SRC_DIR/configure --prefix=$OUT_DIR          \
                        --cpu=$MACHINE             \
                        --target-list=$TARGET_LIST \
-                       --audio-drv-list=alsa      \
+                       --audio-drv-list=$AUDIO    \
                        --disable-bzip2            \
                        --disable-docs             \
                        --disable-gcrypt           \
@@ -116,7 +139,7 @@ if [[ ! -d $STEP_DIR ]]; then
                        --disable-snappy           \
                        --disable-vnc              \
                        --disable-xen              \
-                       --enable-sdl               || exit 6
+                       --enable-$DISPLAY               || exit 6
 #                       --static                   \
 
     make -j$JOBS &&
